SDL=`sdl2-config --cflags --libs` -lSDL2 -lSDL2_mixer -lSDL2_image -lSDL2_ttf
GCC=g++
FLAGS=-c -Wall
NAME=Simulator
G=git

all: push

push: commit
	$(G) push

commit: index
	$(G) commit -m "commit"

index: program
	$(G) add .

program: main.o execute.o state.o graphic.o input.o keylistener.o entity.o
	$(GCC) main.o execute.o state.o graphic.o input.o keylistener.o entity.o -o $(NAME) $(SDL)

main.o: mainheader.h main.cpp
	$(GCC) $(FLAGS) main.cpp

execute.o: execute.h execute.cpp
	$(GCC) $(FLAGS) execute.h execute.cpp

state.o: state.h state.cpp
	$(GCC) $(FLAGS) state.h state.cpp

graphic.o: graphic.h graphic.cpp
	$(GCC) $(FLAGS) graphic.h graphic.cpp $(SDL)

input.o: input.h input.cpp
	$(GCC) $(FLAGS) input.h input.cpp $(SDL)

keylistener.o: input_listener.cpp
	$(GCC) $(FLAGS) input_listener.cpp $(SDL)

entity.o: entity.h entity.cpp
	$(GCC) $(FLAGS) entity.h entity.cpp
